### ISSUE TITLE
The warm_start=True attribute in the VQC class is broken

### ISSUE THREAD

**Issue by bb511** [Qiskit/qiskit-machine-learning#296]
### Environment

- **Qiskit Machine Learning version**: 0.3.0
- **Python version**: 3.9.7
- **Operating system**: Red Hat 7.9

### What is happening?

Trying to perform two or more fits with the current VQC class, when `warm_start=True`, produces the following error:
```
Traceback (most recent call last):
  File "/work/deodagiu/bug_examples/vqc_warm_start.py", line 33, in <module>
    vqc.fit(data[10:, :], onehot_target[10:])
  File "/work/deodagiu/miniconda/envs/qiskit_bugs/lib/python3.9/site-packages/qiskit_machine_learning/algorithms/classifiers/vqc.py", line 167, in fit
    return super().fit(X, y)
  File "/work/deodagiu/miniconda/envs/qiskit_bugs/lib/python3.9/site-packages/qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py", line 109, in fit
    x0=self._choose_initial_point(),
  File "/work/deodagiu/miniconda/envs/qiskit_bugs/lib/python3.9/site-packages/qiskit_machine_learning/algorithms/trainable_model.py", line 204, in _choose_initial_point
    self._initial_point = self._fit_result[0]
TypeError: 'OptimizerResult' object is not subscriptable
```
**This bug was introduced with 0.3.0. In previous versions, `warm_start=True` did not produce this issue.**

### How can we reproduce the issue?

Run the following code:
```
from time import perf_counter
import numpy as np

from qiskit.utils import QuantumInstance
from qiskit_machine_learning.algorithms.classifiers import VQC
from qiskit import Aer

# Choose a seed for the quantum instance initialisation.
seed = 123

# Construct toy data set.
data = np.random.rand(20, 4)
target = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
target = np.tile(target, 2)

# Onehot encode the target.
onehot_target = np.zeros((target.size, int(target.max() + 1)))
onehot_target[np.arange(target.size), target.astype(int)] = 1

# Initialise the VQC.
backend = Aer.get_backend("aer_simulator_statevector")
qin = QuantumInstance(backend, seed_simulator=seed, seed_transpiler=seed)
vqc = VQC(num_qubits=4, feature_map=None, ansatz=None, loss='cross_entropy',
          optimizer=None, warm_start=True, quantum_instance=qin,
          initial_point=None, callback=None)

# Fit the VQC to the constructed toy data. Time the fit.
fit_time_init = perf_counter()
vqc.fit(data[:10, :], onehot_target[:10])
fit_time_fina = perf_counter()
print(f"Fit completed in: {fit_time_fina-fit_time_init:.2e} s")
fit_time_init = perf_counter()
vqc.fit(data[10:, :], onehot_target[10:])
fit_time_fina = perf_counter()
print(f"Fit completed in: {fit_time_fina-fit_time_init:.2e} s")
```

The output of this code is shown in the **What is happening?** section.

### What should happen?

The VQC should complete the fit without any issues.

**Comment by woodsp-ibm** [comment]
In Terra the optimizers were refactored and the old `optimize` method, that returned a tuple (subscriptable) was deprecated and a new method `minimize` was created that returns OptimizerResult object. I looks like the code was updated to the new method but the return/result handling was not altered - leading to the failure you see.
