### ISSUE TITLE
Error when running TorchRuntimeClient

### ISSUE THREAD

**Issue by EliasCombarro** [Qiskit/qiskit-machine-learning#527]
### Environment

- **Qiskit Machine Learning version**: 0.4.0 and 0.5.0
- **Python version**: 3.7.15
- **Operating system**: Google Colab

### What is happening?

When using TorchRuntimeClient, it fails with the following error (taken from the log of the job):

2022-11-16T07:37:37.332393231Z --- Logging error ---
2022-11-16T07:37:37.335383631Z Traceback (most recent call last):
2022-11-16T07:37:37.335438588Z   File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-16T07:37:37.335466993Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-16T07:37:37.335499686Z   File "/code/./program.py", line 502, in main
2022-11-16T07:37:37.335520910Z     ret = trainer.train()
2022-11-16T07:37:37.335545397Z   File "/code/./program.py", line 221, in train
2022-11-16T07:37:37.335625843Z     loss, t_fwd, t_bckwd = self.train_step(train_batch)
2022-11-16T07:37:37.335644144Z   File "/code/./program.py", line 293, in train_step
2022-11-16T07:37:37.335662319Z     self.optimizer.step()
2022-11-16T07:37:37.335679267Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
2022-11-16T07:37:37.335744542Z     out = func(*args, **kwargs)
2022-11-16T07:37:37.335790758Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
2022-11-16T07:37:37.335813894Z     ret = func(self, *args, **kwargs)
2022-11-16T07:37:37.335837831Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/adam.py", line 214, in step
2022-11-16T07:37:37.335863581Z     if self.defaults['capturable'] or self.defaults['fused']
2022-11-16T07:37:37.335885565Z KeyError: 'fused'
2022-11-16T07:37:37.335929568Z 
2022-11-16T07:37:37.335946623Z During handling of the above exception, another exception occurred:
2022-11-16T07:37:37.335963172Z 
2022-11-16T07:37:37.335991995Z Traceback (most recent call last):
2022-11-16T07:37:37.336010325Z   File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
2022-11-16T07:37:37.336049729Z     msg = self.format(record)
2022-11-16T07:37:37.336065098Z   File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
2022-11-16T07:37:37.336082152Z     return fmt.format(record)
2022-11-16T07:37:37.336198160Z   File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
2022-11-16T07:37:37.336366939Z     record.message = record.getMessage()
2022-11-16T07:37:37.336391059Z   File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
2022-11-16T07:37:37.336410227Z     msg = msg % self.args
2022-11-16T07:37:37.336459186Z TypeError: not all arguments converted during string formatting
2022-11-16T07:37:37.336477951Z Call stack:
2022-11-16T07:37:37.336596920Z   File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
2022-11-16T07:37:37.336679861Z     self._bootstrap_inner()
2022-11-16T07:37:37.336700948Z   File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
2022-11-16T07:37:37.336725819Z     self.run()
2022-11-16T07:37:37.336744522Z   File "/opt/app-root/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2022-11-16T07:37:37.336762596Z     result = context.run(func, *args)
2022-11-16T07:37:37.336780238Z   File "/provider/server/main.py", line 75, in execute_program
2022-11-16T07:37:37.336797858Z     starter.execute()
2022-11-16T07:37:37.336816243Z   File "/provider/programruntime/program_starter_wrapper.py", line 92, in execute
2022-11-16T07:37:37.336833844Z     logger.error(
2022-11-16T07:37:37.336851598Z Message: 'Error executing program job cdq96djcgdedhj0apec0'
2022-11-16T07:37:37.336873987Z Arguments: (KeyError('fused'),)
2022-11-16T07:37:37.336940229Z webserver-starter - ERROR Failed to execute program: 'fused'
2022-11-16T07:37:37.336959480Z Traceback (most recent call last):
2022-11-16T07:37:37.336977111Z   File "/provider/server/main.py", line 75, in execute_program
2022-11-16T07:37:37.336998211Z     starter.execute()
2022-11-16T07:37:37.337016918Z   File "/provider/programruntime/program_starter_wrapper.py", line 96, in execute
2022-11-16T07:37:37.337035462Z     raise ex
2022-11-16T07:37:37.337057385Z   File "/provider/programruntime/program_starter_wrapper.py", line 88, in execute
2022-11-16T07:37:37.337075587Z     final_result = self.main(backend, self.messenger, **self.user_params)
2022-11-16T07:37:37.337093184Z   File "/code/./program.py", line 502, in main
2022-11-16T07:37:37.337108520Z     ret = trainer.train()
2022-11-16T07:37:37.337127089Z   File "/code/./program.py", line 221, in train
2022-11-16T07:37:37.337143146Z     loss, t_fwd, t_bckwd = self.train_step(train_batch)
2022-11-16T07:37:37.337160520Z   File "/code/./program.py", line 293, in train_step
2022-11-16T07:37:37.337176835Z     self.optimizer.step()
2022-11-16T07:37:37.337197548Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
2022-11-16T07:37:37.337214349Z     out = func(*args, **kwargs)
2022-11-16T07:37:37.337232286Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
2022-11-16T07:37:37.337544979Z     ret = func(self, *args, **kwargs)
2022-11-16T07:37:37.337579685Z   File "/opt/app-root/lib64/python3.8/site-packages/torch/optim/adam.py", line 214, in step
2022-11-16T07:37:37.337602418Z     if self.defaults['capturable'] or self.defaults['fused']
2022-11-16T07:37:37.337627948Z KeyError: 'fused'
2022-11-16T07:37:37.352319665Z jaeger_tracing - INFO Span publisher exited
2022-11-16T07:37:37.352881613Z webserver-starter - DEBUG Writing job status to termination marker file: '{"status": "Failed"}'

### How can we reproduce the issue?

I have used the code of the TorchRuntimeClient that used to be on Qiskit's website (it fails both with ibmq_qasm_simulator and all real devices I have tried):

import numpy as np
import matplotlib.pyplot as plt

from torch import Tensor, manual_seed, is_tensor
from torch.nn import Linear, CrossEntropyLoss, MSELoss
from torch.optim import LBFGS, Adam
from torch.utils.data import Dataset, DataLoader

from qiskit import Aer, QuantumCircuit
from qiskit.utils import QuantumInstance, algorithm_globals
from qiskit.opflow import AerPauliExpectation
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes, ZZFeatureMap
from qiskit_machine_learning.neural_networks import CircuitQNN, TwoLayerQNN
from qiskit_machine_learning.connectors import TorchConnector
from qiskit_machine_learning.runtime import TorchRuntimeClient, TorchRuntimeResult

seed = 42
manual_seed(seed)
algorithm_globals.random_seed = seed

# Generate random dataset

# Select dataset dimension (num_inputs) and size (num_samples)
num_inputs = 2
num_samples = 20

# Generate random input coordinates (X) and binary labels (y)
X = 2 * algorithm_globals.random.random([num_samples, num_inputs]) - 1
y01 = 1 * (np.sum(X, axis=1) >= 0)  # in { 0,  1}, y01 will be used for CircuitQNN example
y = 2 * y01 - 1  # in {-1, +1}, y will be used for OplowQNN example

# Convert to torch Tensors
X_ = Tensor(X)
y01_ = Tensor(y01).reshape(len(y)).long()
y_ = Tensor(y).reshape(len(y), 1)

# Plot dataset
for x, y_target in zip(X, y):
    if y_target == 1:
        plt.plot(x[0], x[1], "bo")
    else:
        plt.plot(x[0], x[1], "go")
plt.plot([-1, 1], [1, -1], "--", color="black")
plt.show()

# Create custom torch dataset class
class TorchDataset(Dataset):
    """Map-style dataset"""

    def __init__(self, X, y):
        self.X = Tensor(X)
        self.y = Tensor(y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        import torch

        if torch.is_tensor(idx):
            idx = idx.tolist()

        X_i = self.X[idx]
        y_i = self.y[idx]

        # important: the dataset item must be returned as data,target
        return X_i, y_i

y = y.reshape(20, 1)
train_set = TorchDataset(X, y)
train_loader = DataLoader(train_set, batch_size=1, shuffle=False)

# Set up QNN
qnn = TwoLayerQNN(num_qubits=num_inputs)
print(qnn.operator)

# Set up PyTorch module
initial_weights = 0.1 * (2 * algorithm_globals.random.random(qnn.num_weights) - 1)
model = TorchConnector(qnn, initial_weights=initial_weights)
print("Initial weights: ", initial_weights)

# Define optimizer and loss
optimizer = Adam(model.parameters(), lr=0.1)
loss_func = MSELoss(reduction="sum")

from qiskit.providers.ibmq import *
token="*****" # Token deleted for privacy
IBMQ.save_account(token)

provider = IBMQ.load_account()

backend=provider.get_backend("ibmq_qasm_simulator")

torch_runtime_client = TorchRuntimeClient(
    provider=provider,
    model=model,
    optimizer=optimizer,
    loss_func=loss_func,
    epochs=5,
    backend=backend,
)

fit_result = torch_runtime_client.fit(train_loader=train_loader, seed=42)

print("id: ", fit_result.job_id)
print("execution time: ", fit_result.execution_time)

### What should happen?

Last week (iirc) this code worked with no problems.

**Comment by adekusar-drl** [comment]
This is a server side problem and I don't think it can be fixed here. @woodsp-ibm can you transfer it to the qiskit-ibm-runtime repo?

**Comment by woodsp-ibm** [comment]
> This is a server side problem and I don't think it can be fixed here. @woodsp-ibm can you transfer it to the qiskit-ibm-runtime repo?

I do not have the necessary permission on qiskit-ibm-runtime- maybe @mtreinish has and can oblige?

**Comment by woodsp-ibm** [comment]
Closing as the author opened an issue directly on qiskit runtime Qiskit/qiskit-ibm-runtime#631
