### ISSUE TITLE
 `TestTorchConnector` fails intermittently

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#87]
### Information

- **Qiskit Machine Learning version**: latest
- **Python version**: All
- **Operating system**: All

### What is the current behavior?
`TestTorchConnector` fails intermittently with exceptions like here:
```
test.connectors.test_torch_connector.TestTorchConnector.test_circuit_qnn_1_8_4
------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/machine_learning_test_case.py", line 49, in wrapper
    test_item(self, *args)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/connectors/test_torch_connector.py", line 365, in test_circuit_qnn_1_8
    self.validate_output_shape(model, test_data)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/connectors/test_torch_connector.py", line 107, in validate_output_shape
    self.assertEqual(c_worked, q_worked)

      File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: True != False

test.connectors.test_torch_connector.TestTorchConnector.test_circuit_qnn_1_1_1__None__None__False___sv__
--------------------------------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/ddt.py", line 182, in wrapper
    return func(self, *args, **kwargs)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/machine_learning_test_case.py", line 49, in wrapper
    test_item(self, *args)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/connectors/test_torch_connector.py", line 309, in test_circuit_qnn_1_1
    self.validate_output_shape(model, test_data)

      File "/home/runner/work/qiskit-machine-learning/qiskit-machine-learning/test/connectors/test_torch_connector.py", line 107, in validate_output_shape
    self.assertEqual(c_worked, q_worked)

      File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/unittest/case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)

      File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/unittest/case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)

    AssertionError: True != False
```

### Steps to reproduce the problem
Run the test several times. There are no specific conditions observed.

### What is the expected behavior?
The test should pass every time.

**Comment by manoelmarques** [comment]
I created a PR #88 where I added seed and logging to help diagnose the problem. It happens randomly at test_torch_connector.py -> test_circuit_qnn_1_1 (with different inputs) -> validate_output_shape method:
```
# test quantum model and track whether it failed or store the output shape
q_worked = True
try:
    q_shape = model(x).shape
except Exception as ex:  # pylint: disable=broad-except
    self.log.debug("q_worked False: %s", str(ex))
    print("q_worked False:", str(ex))
    q_worked = False
```
When it fails, the model always throws the same exception: "array must not contain infs or NaNs", however 'c_shape = linear(x).shape' passes which causes c_worked to be True and q_worked False, failing the test.

I ran several tests and in the Github Actions history there are more than one examples with this same output.

**Comment by adekusar-drl** [comment]
@manoelmarques Thanks a lot! Your logs helped to find the cause of this problem. I think we should replace `Tensor(1)` with `Tensor([1])` in the test.
